/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelBottom;

import javax.swing.table.DefaultTableModel;
import panel.PanelPromo;
import Customer.HalamanUtama;
/**
 *
 * @author user
 */
public class PanelRincian1 extends javax.swing.JPanel {
    private static PanelRincian1 instance;
    private DefaultTableModel tableModel;
    private HalamanUtama halamanUtama; // Referensi ke HalamanUtama    

    /**
     * Creates new form PanelRincian1
     */
    private PanelRincian1() {
        this.halamanUtama = halamanUtama; // Simpan referensi ke HalamanUtama

        // Inisialisasi model tabel
        String[] columnNames = {"ID Menu", "Nama Menu", "Harga", "Jumlah", "Total"};
        tableModel = new DefaultTableModel(columnNames, 0);

        initComponents(); // Pastikan panel memiliki UI
    }

    public static PanelRincian1 getInstance() {
        if (instance == null) {
            instance = new PanelRincian1();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        BayarBtn = new javax.swing.JButton();
        lbJumlahBayar = new javax.swing.JLabel();
        lbJumlahTotalPesanan = new javax.swing.JLabel();
        JumlahBayarField = new javax.swing.JLabel();
        TotalPsnanField = new javax.swing.JLabel();
        RiwayaPsnanBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu Id", "Menu", "Harga", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Rincian Pesanan");

        ExitBtn.setBackground(new java.awt.Color(255, 0, 0));
        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Batalkan");

        BayarBtn.setText("Bayar");
        BayarBtn.setEnabled(false);
        BayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarBtnActionPerformed(evt);
            }
        });

        lbJumlahBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbJumlahBayar.setText("Jumlah Bayar  :");

        lbJumlahTotalPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbJumlahTotalPesanan.setText("Total Pesanan :");

        JumlahBayarField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TotalPsnanField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RiwayaPsnanBtn.setBackground(new java.awt.Color(255, 255, 0));
        RiwayaPsnanBtn.setText("Riwayat Pesanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ExitBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RiwayaPsnanBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JumlahBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CancelBtn)
                                .addGap(18, 18, 18)
                                .addComponent(BayarBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbJumlahTotalPesanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TotalPsnanField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbJumlahBayar)
                                .addComponent(lbJumlahTotalPesanan))
                            .addComponent(JumlahBayarField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TotalPsnanField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitBtn)
                    .addComponent(CancelBtn)
                    .addComponent(BayarBtn)
                    .addComponent(RiwayaPsnanBtn))
                .addGap(17, 17, 17))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed

    }//GEN-LAST:event_ExitBtnActionPerformed

    private void BayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarBtnActionPerformed

    public DefaultTableModel getRincianTableModel() {
        // Akses panelRincian1 melalui HalamanUtama
        return halamanUtama.getPanelRincian1().getTableModel();
    }
    
        // Getter untuk DefaultTableModel
    public DefaultTableModel getTableModel() {
        return tableModel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarBtn;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel JumlahBayarField;
    private javax.swing.JButton RiwayaPsnanBtn;
    private javax.swing.JLabel TotalPsnanField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbJumlahBayar;
    private javax.swing.JLabel lbJumlahTotalPesanan;
    // End of variables declaration//GEN-END:variables
}
